package com.myspace.risk;
/*
// Start Ruleflow
rule "Start Ruleflow" 
    salience 50
    dialect "mvel"

    when
    then
        System.out.println("Rule fired: " + drools.getRule().getName());
        //System.out.println("Starting Ruleflow...risk.simple-ruleflow");
        //kcontext.getKnowledgeRuntime().startProcess("risk.simple-ruleflow");
        System.out.println("Starting Ruleflow...risk.credit-assessment");
        kcontext.getKnowledgeRuntime().startProcess("risk.credit-assessment");
end
*/
/*
// Debug if Applicant is not in working memory
rule "Debug not working memory" 
    salience 100
    dialect "mvel"

    when
        not Applicant()
    then
        System.out.println("Rule fired: " + drools.getRule().getName());
        System.out.println("Debugging: Applicant is not in working memory.");
end

// Debug if Applicant is not in working memory
rule "Debug in working memory" 
    salience 100
    dialect "mvel"

    when
        $app: Applicant()
    then
        System.out.println("Rule fired: " + drools.getRule().getName());
        System.out.println("Debugging: Applicant: " + $app);
end
*/

